name: Check Commits
on: pull_request

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - uses: javier-godoy/action-conventional-commits@master
    
    - name: Get version
      run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    
    - name: Print version
      run: echo "Semver level is ${{ fromJSON(env.SEMVER_LEVEL) }}"
      
    - name: Check snapshot version
      if: ${{ !endsWith( env.VERSION , '-SNAPSHOT' ) }}
      uses: actions/github-script@v3
      with: 
          script: core.setFailed('Version is not SNAPSHOT')

    - name: Check if requires minor
      if: ${{ fromJSON(env.SEMVER_LEVEL)==2 && !startsWith( env.VERSION, '0.' ) && !endsWith( env.VERSION, '.0-SNAPSHOT' ) }}
      run: echo "REQUIRES_MINOR=true" >> $GITHUB_ENV

    - name: Check if requires major
      if: ${{ fromJSON(env.SEMVER_LEVEL)==3 && !startsWith( env.VERSION, '0.' ) && !endsWith( env.VERSION, '.0.0-SNAPSHOT' ) }}
      run: echo "REQUIRES_MAJOR=true" >> $GITHUB_ENV

    - name: Test if requires minor
      if: ${{ env.REQUIRES_MINOR }}
      run: echo "REQUIRES_MINOR"

    - name: Test if requires major
      if: ${{ env.REQUIRES_MAJOR }}
      run: echo "REQUIRES_MAJOR"

    - name: Fail on breaking changes
      if: ${{ fromJSON(env.SEMVER_LEVEL)==3 && !endsWith( env.VERSION , '.0.0-SNAPSHOT' ) && !startsWith( env.VERSION , '0.' ) }}
      uses: actions/github-script@v3
      with: 
          script: core.setFailed("Version ${{ env.VERSION }} cannot contain breaking changes.")
    
    - name: Fail on new features
      if: ${{ fromJSON(env.SEMVER_LEVEL)==2 && !endsWith( env.VERSION , '.0-SNAPSHOT' ) && !startsWith( env.VERSION , '0.' ) }}
      uses: actions/github-script@v3
      with: 
          script: core.setFailed("Version ${{ env.VERSION }} cannot contain new features")       
